services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\User\:
    resource: '%kernel.project_dir%/src/User'

  App\User\Infrastructure\Symfony\Controller\:
    resource: '%kernel.project_dir%/src/User/Infrastructure/Symfony/Controller'
    tags: [ 'controller.service_arguments' ]

